
// Auto-generated by AutoPilot on 29-07-2023 at 02:20:40

const express = require('express');
const router = express.Router();

router.get('/wc11', (req, res) => {
    // Create array of players in the team
    const players = ["MS Dhoni (c & wk)", "Virender Sehwag", "Gautam Gambhir", "Yuvraj Singh", "Suresh Raina", "Yusuf Pathan", "Ravindra Jadeja", "Harbhajan Singh", "Zaheer Khan", "Munaf Patel", "Ashish Nehra", "Piyush Chawla", "Sachin Tendulkar", "Virat Kohli", "Praveen Kumar"];

    // Return the players array
    res.send(players);
});

module.exports = router;